// This file is auto-generated by @hey-api/openapi-ts

import type { DefaultError, UseMutationOptions } from "@tanstack/react-query"

import {
    createPerson,
    deletePerson,
    login,
    type Options,
    register,
} from "../sdk.gen"
import type {
    CreatePersonData,
    CreatePersonError,
    CreatePersonResponse,
    DeletePersonData,
    DeletePersonError,
    DeletePersonResponse,
    LoginData,
    LoginError,
    LoginResponse,
    RegisterData,
} from "../types.gen"

export const registerMutation = (
    options?: Partial<Options<RegisterData>>
): UseMutationOptions<unknown, DefaultError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<
        unknown,
        DefaultError,
        Options<RegisterData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Login a user.
 */
export const loginMutation = (
    options?: Partial<Options<LoginData>>
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<
        LoginResponse,
        LoginError,
        Options<LoginData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Delete an existing person by user id.
 */
export const deletePersonMutation = (
    options?: Partial<Options<DeletePersonData>>
): UseMutationOptions<
    DeletePersonResponse,
    DeletePersonError,
    Options<DeletePersonData>
> => {
    const mutationOptions: UseMutationOptions<
        DeletePersonResponse,
        DeletePersonError,
        Options<DeletePersonData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePerson({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Create a new person that can be assigned to locks, roles, etc.
 */
export const createPersonMutation = (
    options?: Partial<Options<CreatePersonData>>
): UseMutationOptions<
    CreatePersonResponse,
    CreatePersonError,
    Options<CreatePersonData>
> => {
    const mutationOptions: UseMutationOptions<
        CreatePersonResponse,
        CreatePersonError,
        Options<CreatePersonData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPerson({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}
