// This file is auto-generated by @hey-api/openapi-ts

import {
    type DefaultError,
    queryOptions,
    type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
    addVendorData,
    createPerson,
    createUser,
    deletePerson,
    getAllAuditLogsPaged,
    getAllVendorData,
    getLocksPaged,
    getPersonsCount,
    getPersonsPaged,
    getUser,
    getUsersPaged,
    getVendorData,
    implementedVendors,
    login,
    type Options,
    resetPassword,
    syncLocks,
} from "../sdk.gen"
import type {
    AddVendorDataData,
    AddVendorDataError,
    AddVendorDataResponse,
    CreatePersonData,
    CreatePersonError,
    CreatePersonResponse,
    CreateUserData,
    CreateUserError,
    CreateUserResponse,
    DeletePersonData,
    DeletePersonError,
    DeletePersonResponse,
    GetAllAuditLogsPagedData,
    GetAllAuditLogsPagedError,
    GetAllAuditLogsPagedResponse,
    GetAllVendorDataData,
    GetAllVendorDataError,
    GetAllVendorDataResponse,
    GetLocksPagedData,
    GetLocksPagedError,
    GetLocksPagedResponse,
    GetPersonsCountData,
    GetPersonsCountError,
    GetPersonsCountResponse,
    GetPersonsPagedData,
    GetPersonsPagedError,
    GetPersonsPagedResponse,
    GetUserData,
    GetUserError,
    GetUserResponse,
    GetUsersPagedData,
    GetUsersPagedError,
    GetUsersPagedResponse,
    GetVendorDataData,
    GetVendorDataError,
    GetVendorDataResponse,
    ImplementedVendorsData,
    ImplementedVendorsResponse,
    LoginData,
    LoginError,
    LoginResponse,
    ResetPasswordData,
    ResetPasswordError,
    ResetPasswordResponse,
    SyncLocksData,
    SyncLocksError,
    SyncLocksResponse,
} from "../types.gen"

/**
 * Add new credentials for an implemented vendor.
 */
export const addVendorDataMutation = (
    options?: Partial<Options<AddVendorDataData>>
): UseMutationOptions<
    AddVendorDataResponse,
    AddVendorDataError,
    Options<AddVendorDataData>
> => {
    const mutationOptions: UseMutationOptions<
        AddVendorDataResponse,
        AddVendorDataError,
        Options<AddVendorDataData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await addVendorData({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Reset the authenticated user's password.
 */
export const resetPasswordMutation = (
    options?: Partial<Options<ResetPasswordData>>
): UseMutationOptions<
    ResetPasswordResponse,
    ResetPasswordError,
    Options<ResetPasswordData>
> => {
    const mutationOptions: UseMutationOptions<
        ResetPasswordResponse,
        ResetPasswordError,
        Options<ResetPasswordData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await resetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Create a new user (admin only).
 */
export const createUserMutation = (
    options?: Partial<Options<CreateUserData>>
): UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
> => {
    const mutationOptions: UseMutationOptions<
        CreateUserResponse,
        CreateUserError,
        Options<CreateUserData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUser({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Login a user.
 */
export const loginMutation = (
    options?: Partial<Options<LoginData>>
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<
        LoginResponse,
        LoginError,
        Options<LoginData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get all users paginated.
 */
export const getUsersPagedMutation = (
    options?: Partial<Options<GetUsersPagedData>>
): UseMutationOptions<
    GetUsersPagedResponse,
    GetUsersPagedError,
    Options<GetUsersPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetUsersPagedResponse,
        GetUsersPagedError,
        Options<GetUsersPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getUsersPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Delete an existing person by user id.
 */
export const deletePersonMutation = (
    options?: Partial<Options<DeletePersonData>>
): UseMutationOptions<
    DeletePersonResponse,
    DeletePersonError,
    Options<DeletePersonData>
> => {
    const mutationOptions: UseMutationOptions<
        DeletePersonResponse,
        DeletePersonError,
        Options<DeletePersonData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePerson({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Create a new person that can be assigned to locks, roles, etc.
 */
export const createPersonMutation = (
    options?: Partial<Options<CreatePersonData>>
): UseMutationOptions<
    CreatePersonResponse,
    CreatePersonError,
    Options<CreatePersonData>
> => {
    const mutationOptions: UseMutationOptions<
        CreatePersonResponse,
        CreatePersonError,
        Options<CreatePersonData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPerson({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get all persons paginated.
 */
export const getPersonsPagedMutation = (
    options?: Partial<Options<GetPersonsPagedData>>
): UseMutationOptions<
    GetPersonsPagedResponse,
    GetPersonsPagedError,
    Options<GetPersonsPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetPersonsPagedResponse,
        GetPersonsPagedError,
        Options<GetPersonsPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getPersonsPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Sync locks from ISEO. Creates/updates local locks and removes those no longer in ISEO.
 */
export const syncLocksMutation = (
    options?: Partial<Options<SyncLocksData>>
): UseMutationOptions<
    SyncLocksResponse,
    SyncLocksError,
    Options<SyncLocksData>
> => {
    const mutationOptions: UseMutationOptions<
        SyncLocksResponse,
        SyncLocksError,
        Options<SyncLocksData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await syncLocks({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get all locks paginated.
 */
export const getLocksPagedMutation = (
    options?: Partial<Options<GetLocksPagedData>>
): UseMutationOptions<
    GetLocksPagedResponse,
    GetLocksPagedError,
    Options<GetLocksPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetLocksPagedResponse,
        GetLocksPagedError,
        Options<GetLocksPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getLocksPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get all audit logs paginated.
 */
export const getAllAuditLogsPagedMutation = (
    options?: Partial<Options<GetAllAuditLogsPagedData>>
): UseMutationOptions<
    GetAllAuditLogsPagedResponse,
    GetAllAuditLogsPagedError,
    Options<GetAllAuditLogsPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetAllAuditLogsPagedResponse,
        GetAllAuditLogsPagedError,
        Options<GetAllAuditLogsPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getAllAuditLogsPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
        _id: string
        _infinite?: boolean
        tags?: ReadonlyArray<string>
    },
]

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseUrl:
            options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
    } as QueryKey<TOptions>[0]
    if (infinite) {
        params._infinite = infinite
    }
    if (tags) {
        params.tags = tags
    }
    if (options?.body) {
        params.body = options.body
    }
    if (options?.headers) {
        params.headers = options.headers
    }
    if (options?.path) {
        params.path = options.path
    }
    if (options?.query) {
        params.query = options.query
    }
    return [params]
}

export const getVendorDataQueryKey = (options: Options<GetVendorDataData>) =>
    createQueryKey("getVendorData", options)

/**
 * Get one Vendor-Data.
 */
export const getVendorDataOptions = (options: Options<GetVendorDataData>) =>
    queryOptions<
        GetVendorDataResponse,
        GetVendorDataError,
        GetVendorDataResponse,
        ReturnType<typeof getVendorDataQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getVendorData({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getVendorDataQueryKey(options),
    })

export const implementedVendorsQueryKey = (
    options?: Options<ImplementedVendorsData>
) => createQueryKey("implementedVendors", options)

/**
 * Get all implemented lock vendors.
 */
export const implementedVendorsOptions = (
    options?: Options<ImplementedVendorsData>
) =>
    queryOptions<
        ImplementedVendorsResponse,
        DefaultError,
        ImplementedVendorsResponse,
        ReturnType<typeof implementedVendorsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await implementedVendors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: implementedVendorsQueryKey(options),
    })

export const getAllVendorDataQueryKey = (
    options?: Options<GetAllVendorDataData>
) => createQueryKey("getAllVendorData", options)

/**
 * Get all Vendor-Datas.
 */
export const getAllVendorDataOptions = (
    options?: Options<GetAllVendorDataData>
) =>
    queryOptions<
        GetAllVendorDataResponse,
        GetAllVendorDataError,
        GetAllVendorDataResponse,
        ReturnType<typeof getAllVendorDataQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAllVendorData({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getAllVendorDataQueryKey(options),
    })

export const getUserQueryKey = (options: Options<GetUserData>) =>
    createQueryKey("getUser", options)

/**
 * Get a user by id.
 */
export const getUserOptions = (options: Options<GetUserData>) =>
    queryOptions<
        GetUserResponse,
        GetUserError,
        GetUserResponse,
        ReturnType<typeof getUserQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getUserQueryKey(options),
    })

export const getPersonsCountQueryKey = (
    options?: Options<GetPersonsCountData>
) => createQueryKey("getPersonsCount", options)

/**
 * Get the total number of persons.
 */
export const getPersonsCountOptions = (
    options?: Options<GetPersonsCountData>
) =>
    queryOptions<
        GetPersonsCountResponse,
        GetPersonsCountError,
        GetPersonsCountResponse,
        ReturnType<typeof getPersonsCountQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPersonsCount({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getPersonsCountQueryKey(options),
    })
