// This file is auto-generated by @hey-api/openapi-ts

import {
    type DefaultError,
    queryOptions,
    type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
    activateUser,
    addVendorData,
    adminResetPassword,
    changeRole,
    createLock,
    createPerson,
    createUser,
    deactivateUser,
    deletePerson,
    deleteVendorData,
    editUser,
    getAccessGrantsPaged,
    getAllAuditLogsPaged,
    getAllVendorData,
    getLocksCount,
    getLocksPaged,
    getPersonById,
    getPersonsCount,
    getPersonsPaged,
    getUser,
    getUsersPaged,
    getVendorData,
    getVendorSpecificDefinitions,
    grantAccess,
    implementedVendors,
    login,
    type Options,
    requestPasswordChange,
    resetPassword,
    revokeAccess,
    syncLocks,
    updateLock,
    updateVendorData,
} from "../sdk.gen"
import type {
    ActivateUserData,
    ActivateUserError,
    AddVendorDataData,
    AddVendorDataError,
    AddVendorDataResponse,
    AdminResetPasswordData,
    AdminResetPasswordError,
    AdminResetPasswordResponse,
    ChangeRoleData,
    ChangeRoleError,
    CreateLockData,
    CreateLockError,
    CreateLockResponse,
    CreatePersonData,
    CreatePersonError,
    CreatePersonResponse,
    CreateUserData,
    CreateUserError,
    CreateUserResponse,
    DeactivateUserData,
    DeactivateUserError,
    DeletePersonData,
    DeletePersonError,
    DeletePersonResponse,
    DeleteVendorDataData,
    DeleteVendorDataError,
    DeleteVendorDataResponse,
    EditUserData,
    EditUserError,
    GetAccessGrantsPagedData,
    GetAccessGrantsPagedError,
    GetAccessGrantsPagedResponse,
    GetAllAuditLogsPagedData,
    GetAllAuditLogsPagedError,
    GetAllAuditLogsPagedResponse,
    GetAllVendorDataData,
    GetAllVendorDataError,
    GetAllVendorDataResponse,
    GetLocksCountData,
    GetLocksCountError,
    GetLocksCountResponse,
    GetLocksPagedData,
    GetLocksPagedError,
    GetLocksPagedResponse,
    GetPersonByIdData,
    GetPersonByIdError,
    GetPersonByIdResponse,
    GetPersonsCountData,
    GetPersonsCountError,
    GetPersonsCountResponse,
    GetPersonsPagedData,
    GetPersonsPagedError,
    GetPersonsPagedResponse,
    GetUserData,
    GetUserError,
    GetUserResponse,
    GetUsersPagedData,
    GetUsersPagedError,
    GetUsersPagedResponse,
    GetVendorDataData,
    GetVendorDataError,
    GetVendorDataResponse,
    GetVendorSpecificDefinitionsData,
    GetVendorSpecificDefinitionsError,
    GetVendorSpecificDefinitionsResponse,
    GrantAccessData,
    GrantAccessError,
    GrantAccessResponse,
    ImplementedVendorsData,
    ImplementedVendorsResponse,
    LoginData,
    LoginError,
    LoginResponse,
    RequestPasswordChangeData,
    RequestPasswordChangeError,
    ResetPasswordData,
    ResetPasswordError,
    ResetPasswordResponse,
    RevokeAccessData,
    RevokeAccessError,
    RevokeAccessResponse,
    SyncLocksData,
    SyncLocksError,
    SyncLocksResponse,
    UpdateLockData,
    UpdateLockError,
    UpdateLockResponse,
    UpdateVendorDataData,
    UpdateVendorDataError,
    UpdateVendorDataResponse,
} from "../types.gen"

/**
 * Add new credentials for an implemented vendor. Check /definitions/{forVendor} for required metadata fields.
 */
export const addVendorDataMutation = (
    options?: Partial<Options<AddVendorDataData>>
): UseMutationOptions<
    AddVendorDataResponse,
    AddVendorDataError,
    Options<AddVendorDataData>
> => {
    const mutationOptions: UseMutationOptions<
        AddVendorDataResponse,
        AddVendorDataError,
        Options<AddVendorDataData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await addVendorData({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Update one vendor-data.
 */
export const updateVendorDataMutation = (
    options?: Partial<Options<UpdateVendorDataData>>
): UseMutationOptions<
    UpdateVendorDataResponse,
    UpdateVendorDataError,
    Options<UpdateVendorDataData>
> => {
    const mutationOptions: UseMutationOptions<
        UpdateVendorDataResponse,
        UpdateVendorDataError,
        Options<UpdateVendorDataData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateVendorData({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Update a lock.
 */
export const updateLockMutation = (
    options?: Partial<Options<UpdateLockData>>
): UseMutationOptions<
    UpdateLockResponse,
    UpdateLockError,
    Options<UpdateLockData>
> => {
    const mutationOptions: UseMutationOptions<
        UpdateLockResponse,
        UpdateLockError,
        Options<UpdateLockData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateLock({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Reset the authenticated user's password.
 */
export const resetPasswordMutation = (
    options?: Partial<Options<ResetPasswordData>>
): UseMutationOptions<
    ResetPasswordResponse,
    ResetPasswordError,
    Options<ResetPasswordData>
> => {
    const mutationOptions: UseMutationOptions<
        ResetPasswordResponse,
        ResetPasswordError,
        Options<ResetPasswordData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await resetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Request a password change for a user (admin only).
 */
export const requestPasswordChangeMutation = (
    options?: Partial<Options<RequestPasswordChangeData>>
): UseMutationOptions<
    unknown,
    RequestPasswordChangeError,
    Options<RequestPasswordChangeData>
> => {
    const mutationOptions: UseMutationOptions<
        unknown,
        RequestPasswordChangeError,
        Options<RequestPasswordChangeData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await requestPasswordChange({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Edit a user's details (admin only).
 */
export const editUserMutation = (
    options?: Partial<Options<EditUserData>>
): UseMutationOptions<unknown, EditUserError, Options<EditUserData>> => {
    const mutationOptions: UseMutationOptions<
        unknown,
        EditUserError,
        Options<EditUserData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await editUser({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Deactivate a user (admin only).
 */
export const deactivateUserMutation = (
    options?: Partial<Options<DeactivateUserData>>
): UseMutationOptions<
    unknown,
    DeactivateUserError,
    Options<DeactivateUserData>
> => {
    const mutationOptions: UseMutationOptions<
        unknown,
        DeactivateUserError,
        Options<DeactivateUserData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await deactivateUser({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Create a new user (admin only).
 */
export const createUserMutation = (
    options?: Partial<Options<CreateUserData>>
): UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
> => {
    const mutationOptions: UseMutationOptions<
        CreateUserResponse,
        CreateUserError,
        Options<CreateUserData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUser({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Change a user's role (admin only).
 */
export const changeRoleMutation = (
    options?: Partial<Options<ChangeRoleData>>
): UseMutationOptions<unknown, ChangeRoleError, Options<ChangeRoleData>> => {
    const mutationOptions: UseMutationOptions<
        unknown,
        ChangeRoleError,
        Options<ChangeRoleData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await changeRole({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Login a user.
 */
export const loginMutation = (
    options?: Partial<Options<LoginData>>
): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<
        LoginResponse,
        LoginError,
        Options<LoginData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get all users paginated.
 */
export const getUsersPagedMutation = (
    options?: Partial<Options<GetUsersPagedData>>
): UseMutationOptions<
    GetUsersPagedResponse,
    GetUsersPagedError,
    Options<GetUsersPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetUsersPagedResponse,
        GetUsersPagedError,
        Options<GetUsersPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getUsersPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Admin-reset a user's password (admin only). Generates a new password and returns it.
 */
export const adminResetPasswordMutation = (
    options?: Partial<Options<AdminResetPasswordData>>
): UseMutationOptions<
    AdminResetPasswordResponse,
    AdminResetPasswordError,
    Options<AdminResetPasswordData>
> => {
    const mutationOptions: UseMutationOptions<
        AdminResetPasswordResponse,
        AdminResetPasswordError,
        Options<AdminResetPasswordData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await adminResetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Activate a user (admin only).
 */
export const activateUserMutation = (
    options?: Partial<Options<ActivateUserData>>
): UseMutationOptions<
    unknown,
    ActivateUserError,
    Options<ActivateUserData>
> => {
    const mutationOptions: UseMutationOptions<
        unknown,
        ActivateUserError,
        Options<ActivateUserData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await activateUser({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Delete an existing person by user id.
 */
export const deletePersonMutation = (
    options?: Partial<Options<DeletePersonData>>
): UseMutationOptions<
    DeletePersonResponse,
    DeletePersonError,
    Options<DeletePersonData>
> => {
    const mutationOptions: UseMutationOptions<
        DeletePersonResponse,
        DeletePersonError,
        Options<DeletePersonData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePerson({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Create a new person that can be assigned to locks, roles, etc.
 */
export const createPersonMutation = (
    options?: Partial<Options<CreatePersonData>>
): UseMutationOptions<
    CreatePersonResponse,
    CreatePersonError,
    Options<CreatePersonData>
> => {
    const mutationOptions: UseMutationOptions<
        CreatePersonResponse,
        CreatePersonError,
        Options<CreatePersonData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPerson({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get all persons paginated.
 */
export const getPersonsPagedMutation = (
    options?: Partial<Options<GetPersonsPagedData>>
): UseMutationOptions<
    GetPersonsPagedResponse,
    GetPersonsPagedError,
    Options<GetPersonsPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetPersonsPagedResponse,
        GetPersonsPagedError,
        Options<GetPersonsPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getPersonsPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Sync locks from ISEO. Creates/updates local locks and removes those no longer in ISEO.
 */
export const syncLocksMutation = (
    options?: Partial<Options<SyncLocksData>>
): UseMutationOptions<
    SyncLocksResponse,
    SyncLocksError,
    Options<SyncLocksData>
> => {
    const mutationOptions: UseMutationOptions<
        SyncLocksResponse,
        SyncLocksError,
        Options<SyncLocksData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await syncLocks({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Create a new lock for an implemented vendor.
 */
export const createLockMutation = (
    options?: Partial<Options<CreateLockData>>
): UseMutationOptions<
    CreateLockResponse,
    CreateLockError,
    Options<CreateLockData>
> => {
    const mutationOptions: UseMutationOptions<
        CreateLockResponse,
        CreateLockError,
        Options<CreateLockData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await createLock({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get all locks paginated.
 */
export const getLocksPagedMutation = (
    options?: Partial<Options<GetLocksPagedData>>
): UseMutationOptions<
    GetLocksPagedResponse,
    GetLocksPagedError,
    Options<GetLocksPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetLocksPagedResponse,
        GetLocksPagedError,
        Options<GetLocksPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getLocksPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get all audit logs paginated.
 */
export const getAllAuditLogsPagedMutation = (
    options?: Partial<Options<GetAllAuditLogsPagedData>>
): UseMutationOptions<
    GetAllAuditLogsPagedResponse,
    GetAllAuditLogsPagedError,
    Options<GetAllAuditLogsPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetAllAuditLogsPagedResponse,
        GetAllAuditLogsPagedError,
        Options<GetAllAuditLogsPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getAllAuditLogsPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Grant a person permission to open a lock for a time window.
 */
export const grantAccessMutation = (
    options?: Partial<Options<GrantAccessData>>
): UseMutationOptions<
    GrantAccessResponse,
    GrantAccessError,
    Options<GrantAccessData>
> => {
    const mutationOptions: UseMutationOptions<
        GrantAccessResponse,
        GrantAccessError,
        Options<GrantAccessData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await grantAccess({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Revoke a person's permission to open a lock.
 */
export const revokeAccessMutation = (
    options?: Partial<Options<RevokeAccessData>>
): UseMutationOptions<
    RevokeAccessResponse,
    RevokeAccessError,
    Options<RevokeAccessData>
> => {
    const mutationOptions: UseMutationOptions<
        RevokeAccessResponse,
        RevokeAccessError,
        Options<RevokeAccessData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await revokeAccess({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Get access grants paginated, optionally filtered by person or lock.
 */
export const getAccessGrantsPagedMutation = (
    options?: Partial<Options<GetAccessGrantsPagedData>>
): UseMutationOptions<
    GetAccessGrantsPagedResponse,
    GetAccessGrantsPagedError,
    Options<GetAccessGrantsPagedData>
> => {
    const mutationOptions: UseMutationOptions<
        GetAccessGrantsPagedResponse,
        GetAccessGrantsPagedError,
        Options<GetAccessGrantsPagedData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await getAccessGrantsPaged({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

/**
 * Delete one vendor-data by id.
 */
export const deleteVendorDataMutation = (
    options?: Partial<Options<DeleteVendorDataData>>
): UseMutationOptions<
    DeleteVendorDataResponse,
    DeleteVendorDataError,
    Options<DeleteVendorDataData>
> => {
    const mutationOptions: UseMutationOptions<
        DeleteVendorDataResponse,
        DeleteVendorDataError,
        Options<DeleteVendorDataData>
    > = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteVendorData({
                ...options,
                ...fnOptions,
                throwOnError: true,
            })
            return data
        },
    }
    return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
        _id: string
        _infinite?: boolean
        tags?: ReadonlyArray<string>
    },
]

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseUrl:
            options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
    } as QueryKey<TOptions>[0]
    if (infinite) {
        params._infinite = infinite
    }
    if (tags) {
        params.tags = tags
    }
    if (options?.body) {
        params.body = options.body
    }
    if (options?.headers) {
        params.headers = options.headers
    }
    if (options?.path) {
        params.path = options.path
    }
    if (options?.query) {
        params.query = options.query
    }
    return [params]
}

export const getVendorDataQueryKey = (options: Options<GetVendorDataData>) =>
    createQueryKey("getVendorData", options)

/**
 * Get one Vendor-Data.
 */
export const getVendorDataOptions = (options: Options<GetVendorDataData>) =>
    queryOptions<
        GetVendorDataResponse,
        GetVendorDataError,
        GetVendorDataResponse,
        ReturnType<typeof getVendorDataQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getVendorData({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getVendorDataQueryKey(options),
    })

export const implementedVendorsQueryKey = (
    options?: Options<ImplementedVendorsData>
) => createQueryKey("implementedVendors", options)

/**
 * Get all implemented lock vendors.
 */
export const implementedVendorsOptions = (
    options?: Options<ImplementedVendorsData>
) =>
    queryOptions<
        ImplementedVendorsResponse,
        DefaultError,
        ImplementedVendorsResponse,
        ReturnType<typeof implementedVendorsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await implementedVendors({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: implementedVendorsQueryKey(options),
    })

export const getVendorSpecificDefinitionsQueryKey = (
    options: Options<GetVendorSpecificDefinitionsData>
) => createQueryKey("getVendorSpecificDefinitions", options)

/**
 * Get vendor specific fields that should be sent when creating a new vendor-data.
 */
export const getVendorSpecificDefinitionsOptions = (
    options: Options<GetVendorSpecificDefinitionsData>
) =>
    queryOptions<
        GetVendorSpecificDefinitionsResponse,
        GetVendorSpecificDefinitionsError,
        GetVendorSpecificDefinitionsResponse,
        ReturnType<typeof getVendorSpecificDefinitionsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getVendorSpecificDefinitions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getVendorSpecificDefinitionsQueryKey(options),
    })

export const getAllVendorDataQueryKey = (
    options?: Options<GetAllVendorDataData>
) => createQueryKey("getAllVendorData", options)

/**
 * Get all Vendor-Datas.
 */
export const getAllVendorDataOptions = (
    options?: Options<GetAllVendorDataData>
) =>
    queryOptions<
        GetAllVendorDataResponse,
        GetAllVendorDataError,
        GetAllVendorDataResponse,
        ReturnType<typeof getAllVendorDataQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAllVendorData({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getAllVendorDataQueryKey(options),
    })

export const getUserQueryKey = (options: Options<GetUserData>) =>
    createQueryKey("getUser", options)

/**
 * Get a user by id.
 */
export const getUserOptions = (options: Options<GetUserData>) =>
    queryOptions<
        GetUserResponse,
        GetUserError,
        GetUserResponse,
        ReturnType<typeof getUserQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getUserQueryKey(options),
    })

export const getPersonByIdQueryKey = (options: Options<GetPersonByIdData>) =>
    createQueryKey("getPersonById", options)

/**
 * Get an existing person by id.
 */
export const getPersonByIdOptions = (options: Options<GetPersonByIdData>) =>
    queryOptions<
        GetPersonByIdResponse,
        GetPersonByIdError,
        GetPersonByIdResponse,
        ReturnType<typeof getPersonByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPersonById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getPersonByIdQueryKey(options),
    })

export const getPersonsCountQueryKey = (
    options?: Options<GetPersonsCountData>
) => createQueryKey("getPersonsCount", options)

/**
 * Get the total number of persons.
 */
export const getPersonsCountOptions = (
    options?: Options<GetPersonsCountData>
) =>
    queryOptions<
        GetPersonsCountResponse,
        GetPersonsCountError,
        GetPersonsCountResponse,
        ReturnType<typeof getPersonsCountQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPersonsCount({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getPersonsCountQueryKey(options),
    })

export const getLocksCountQueryKey = (options?: Options<GetLocksCountData>) =>
    createQueryKey("getLocksCount", options)

/**
 * Get the total number of locks.
 */
export const getLocksCountOptions = (options?: Options<GetLocksCountData>) =>
    queryOptions<
        GetLocksCountResponse,
        GetLocksCountError,
        GetLocksCountResponse,
        ReturnType<typeof getLocksCountQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getLocksCount({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true,
            })
            return data
        },
        queryKey: getLocksCountQueryKey(options),
    })
