// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
    ActivateUserData,
    ActivateUserErrors,
    ActivateUserResponses,
    AddVendorDataData,
    AddVendorDataErrors,
    AddVendorDataResponses,
    AdminResetPasswordData,
    AdminResetPasswordErrors,
    AdminResetPasswordResponses,
    ChangeRoleData,
    ChangeRoleErrors,
    ChangeRoleResponses,
    CreatePersonData,
    CreatePersonErrors,
    CreatePersonResponses,
    CreateUserData,
    CreateUserErrors,
    CreateUserResponses,
    DeactivateUserData,
    DeactivateUserErrors,
    DeactivateUserResponses,
    DeletePersonData,
    DeletePersonErrors,
    DeletePersonResponses,
    DeleteVendorDataData,
    DeleteVendorDataErrors,
    DeleteVendorDataResponses,
    EditUserData,
    EditUserErrors,
    EditUserResponses,
    GetAccessGrantsPagedData,
    GetAccessGrantsPagedErrors,
    GetAccessGrantsPagedResponses,
    GetAllAuditLogsPagedData,
    GetAllAuditLogsPagedErrors,
    GetAllAuditLogsPagedResponses,
    GetAllVendorDataData,
    GetAllVendorDataErrors,
    GetAllVendorDataResponses,
    GetLocksCountData,
    GetLocksCountErrors,
    GetLocksCountResponses,
    GetLocksPagedData,
    GetLocksPagedErrors,
    GetLocksPagedResponses,
    GetPersonByIdData,
    GetPersonByIdErrors,
    GetPersonByIdResponses,
    GetPersonsCountData,
    GetPersonsCountErrors,
    GetPersonsCountResponses,
    GetPersonsPagedData,
    GetPersonsPagedErrors,
    GetPersonsPagedResponses,
    GetUserData,
    GetUserErrors,
    GetUserResponses,
    GetUsersPagedData,
    GetUsersPagedErrors,
    GetUsersPagedResponses,
    GetVendorDataData,
    GetVendorDataErrors,
    GetVendorDataResponses,
    GetVendorSpecificDefinitionsData,
    GetVendorSpecificDefinitionsErrors,
    GetVendorSpecificDefinitionsResponses,
    GrantAccessData,
    GrantAccessErrors,
    GrantAccessResponses,
    ImplementedVendorsData,
    ImplementedVendorsResponses,
    LoginData,
    LoginErrors,
    LoginResponses,
    RequestPasswordChangeData,
    RequestPasswordChangeErrors,
    RequestPasswordChangeResponses,
    ResetPasswordData,
    ResetPasswordErrors,
    ResetPasswordResponses,
    RevokeAccessData,
    RevokeAccessErrors,
    RevokeAccessResponses,
    SyncLocksData,
    SyncLocksErrors,
    SyncLocksResponses,
    UpdateVendorDataData,
    UpdateVendorDataErrors,
    UpdateVendorDataResponses,
} from "./types.gen"

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

/**
 * Add new credentials for an implemented vendor. Check /definitions/{forVendor} for required metadata fields.
 */
export const addVendorData = <ThrowOnError extends boolean = false>(
    options: Options<AddVendorDataData, ThrowOnError>
) =>
    (options.client ?? client).post<
        AddVendorDataResponses,
        AddVendorDataErrors,
        ThrowOnError
    >({
        url: "/api/v1/vendor-data",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Update one vendor-data.
 */
export const updateVendorData = <ThrowOnError extends boolean = false>(
    options: Options<UpdateVendorDataData, ThrowOnError>
) =>
    (options.client ?? client).put<
        UpdateVendorDataResponses,
        UpdateVendorDataErrors,
        ThrowOnError
    >({
        url: "/api/v1/vendor-data",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Reset the authenticated user's password.
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
    options: Options<ResetPasswordData, ThrowOnError>
) =>
    (options.client ?? client).post<
        ResetPasswordResponses,
        ResetPasswordErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/reset-password",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Request a password change for a user (admin only).
 */
export const requestPasswordChange = <ThrowOnError extends boolean = false>(
    options: Options<RequestPasswordChangeData, ThrowOnError>
) =>
    (options.client ?? client).post<
        RequestPasswordChangeResponses,
        RequestPasswordChangeErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/request-password-change",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Edit a user's details (admin only).
 */
export const editUser = <ThrowOnError extends boolean = false>(
    options: Options<EditUserData, ThrowOnError>
) =>
    (options.client ?? client).post<
        EditUserResponses,
        EditUserErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/edit-user",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Deactivate a user (admin only).
 */
export const deactivateUser = <ThrowOnError extends boolean = false>(
    options: Options<DeactivateUserData, ThrowOnError>
) =>
    (options.client ?? client).post<
        DeactivateUserResponses,
        DeactivateUserErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/deactivate-user",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Create a new user (admin only).
 */
export const createUser = <ThrowOnError extends boolean = false>(
    options: Options<CreateUserData, ThrowOnError>
) =>
    (options.client ?? client).post<
        CreateUserResponses,
        CreateUserErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/create",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Change a user's role (admin only).
 */
export const changeRole = <ThrowOnError extends boolean = false>(
    options: Options<ChangeRoleData, ThrowOnError>
) =>
    (options.client ?? client).post<
        ChangeRoleResponses,
        ChangeRoleErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/change-role",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Login a user.
 */
export const login = <ThrowOnError extends boolean = false>(
    options: Options<LoginData, ThrowOnError>
) =>
    (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        url: "/api/v1/user/auth/login",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Get all users paginated.
 */
export const getUsersPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetUsersPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetUsersPagedResponses,
        GetUsersPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Admin-reset a user's password (admin only). Generates a new password and returns it.
 */
export const adminResetPassword = <ThrowOnError extends boolean = false>(
    options: Options<AdminResetPasswordData, ThrowOnError>
) =>
    (options.client ?? client).post<
        AdminResetPasswordResponses,
        AdminResetPasswordErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/admin-reset-password",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Activate a user (admin only).
 */
export const activateUser = <ThrowOnError extends boolean = false>(
    options: Options<ActivateUserData, ThrowOnError>
) =>
    (options.client ?? client).post<
        ActivateUserResponses,
        ActivateUserErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/activate-user",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Delete an existing person by user id.
 */
export const deletePerson = <ThrowOnError extends boolean = false>(
    options: Options<DeletePersonData, ThrowOnError>
) =>
    (options.client ?? client).post<
        DeletePersonResponses,
        DeletePersonErrors,
        ThrowOnError
    >({
        url: "/api/v1/person/delete",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Create a new person that can be assigned to locks, roles, etc.
 */
export const createPerson = <ThrowOnError extends boolean = false>(
    options: Options<CreatePersonData, ThrowOnError>
) =>
    (options.client ?? client).post<
        CreatePersonResponses,
        CreatePersonErrors,
        ThrowOnError
    >({
        url: "/api/v1/person/create",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Get all persons paginated.
 */
export const getPersonsPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetPersonsPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetPersonsPagedResponses,
        GetPersonsPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/person/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Sync locks from ISEO. Creates/updates local locks and removes those no longer in ISEO.
 */
export const syncLocks = <ThrowOnError extends boolean = false>(
    options?: Options<SyncLocksData, ThrowOnError>
) =>
    (options?.client ?? client).post<
        SyncLocksResponses,
        SyncLocksErrors,
        ThrowOnError
    >({ url: "/api/v1/lock/sync", ...options })

/**
 * Get all locks paginated.
 */
export const getLocksPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetLocksPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetLocksPagedResponses,
        GetLocksPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/lock/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Get all audit logs paginated.
 */
export const getAllAuditLogsPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetAllAuditLogsPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetAllAuditLogsPagedResponses,
        GetAllAuditLogsPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/audit-logs/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Grant a person permission to open a lock for a time window.
 */
export const grantAccess = <ThrowOnError extends boolean = false>(
    options: Options<GrantAccessData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GrantAccessResponses,
        GrantAccessErrors,
        ThrowOnError
    >({
        url: "/api/v1/access-grant",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Revoke a person's permission to open a lock.
 */
export const revokeAccess = <ThrowOnError extends boolean = false>(
    options: Options<RevokeAccessData, ThrowOnError>
) =>
    (options.client ?? client).post<
        RevokeAccessResponses,
        RevokeAccessErrors,
        ThrowOnError
    >({
        url: "/api/v1/access-grant/revoke",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Get access grants paginated, optionally filtered by person or lock.
 */
export const getAccessGrantsPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetAccessGrantsPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetAccessGrantsPagedResponses,
        GetAccessGrantsPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/access-grant/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Delete one vendor-data by id.
 */
export const deleteVendorData = <ThrowOnError extends boolean = false>(
    options: Options<DeleteVendorDataData, ThrowOnError>
) =>
    (options.client ?? client).delete<
        DeleteVendorDataResponses,
        DeleteVendorDataErrors,
        ThrowOnError
    >({ url: "/api/v1/vendor-data/{id}", ...options })

/**
 * Get one Vendor-Data.
 */
export const getVendorData = <ThrowOnError extends boolean = false>(
    options: Options<GetVendorDataData, ThrowOnError>
) =>
    (options.client ?? client).get<
        GetVendorDataResponses,
        GetVendorDataErrors,
        ThrowOnError
    >({ url: "/api/v1/vendor-data/{id}", ...options })

/**
 * Get all implemented lock vendors.
 */
export const implementedVendors = <ThrowOnError extends boolean = false>(
    options?: Options<ImplementedVendorsData, ThrowOnError>
) =>
    (options?.client ?? client).get<
        ImplementedVendorsResponses,
        unknown,
        ThrowOnError
    >({ url: "/api/v1/vendor-data/implemented", ...options })

/**
 * Get vendor specific fields that should be sent when creating a new vendor-data.
 */
export const getVendorSpecificDefinitions = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetVendorSpecificDefinitionsData, ThrowOnError>
) =>
    (options.client ?? client).get<
        GetVendorSpecificDefinitionsResponses,
        GetVendorSpecificDefinitionsErrors,
        ThrowOnError
    >({ url: "/api/v1/vendor-data/definitions/{forVendor}", ...options })

/**
 * Get all Vendor-Datas.
 */
export const getAllVendorData = <ThrowOnError extends boolean = false>(
    options?: Options<GetAllVendorDataData, ThrowOnError>
) =>
    (options?.client ?? client).get<
        GetAllVendorDataResponses,
        GetAllVendorDataErrors,
        ThrowOnError
    >({ url: "/api/v1/vendor-data/all", ...options })

/**
 * Get a user by id.
 */
export const getUser = <ThrowOnError extends boolean = false>(
    options: Options<GetUserData, ThrowOnError>
) =>
    (options.client ?? client).get<
        GetUserResponses,
        GetUserErrors,
        ThrowOnError
    >({ url: "/api/v1/user/{id}", ...options })

/**
 * Get an existing person by id.
 */
export const getPersonById = <ThrowOnError extends boolean = false>(
    options: Options<GetPersonByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<
        GetPersonByIdResponses,
        GetPersonByIdErrors,
        ThrowOnError
    >({ url: "/api/v1/person/{id}", ...options })

/**
 * Get the total number of persons.
 */
export const getPersonsCount = <ThrowOnError extends boolean = false>(
    options?: Options<GetPersonsCountData, ThrowOnError>
) =>
    (options?.client ?? client).get<
        GetPersonsCountResponses,
        GetPersonsCountErrors,
        ThrowOnError
    >({ url: "/api/v1/person/count", ...options })

/**
 * Get the total number of locks.
 */
export const getLocksCount = <ThrowOnError extends boolean = false>(
    options?: Options<GetLocksCountData, ThrowOnError>
) =>
    (options?.client ?? client).get<
        GetLocksCountResponses,
        GetLocksCountErrors,
        ThrowOnError
    >({ url: "/api/v1/lock/count", ...options })
