// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
    AddVendorDataData,
    AddVendorDataErrors,
    AddVendorDataResponses,
    CreatePersonData,
    CreatePersonErrors,
    CreatePersonResponses,
    CreateUserData,
    CreateUserErrors,
    CreateUserResponses,
    DeletePersonData,
    DeletePersonErrors,
    DeletePersonResponses,
    GetAllAuditLogsPagedData,
    GetAllAuditLogsPagedErrors,
    GetAllAuditLogsPagedResponses,
    GetAllVendorDataData,
    GetAllVendorDataErrors,
    GetAllVendorDataResponses,
    GetLocksPagedData,
    GetLocksPagedErrors,
    GetLocksPagedResponses,
    GetPersonsCountData,
    GetPersonsCountErrors,
    GetPersonsCountResponses,
    GetPersonsPagedData,
    GetPersonsPagedErrors,
    GetPersonsPagedResponses,
    GetUserData,
    GetUserErrors,
    GetUserResponses,
    GetUsersPagedData,
    GetUsersPagedErrors,
    GetUsersPagedResponses,
    GetVendorDataData,
    GetVendorDataErrors,
    GetVendorDataResponses,
    ImplementedVendorsData,
    ImplementedVendorsResponses,
    LoginData,
    LoginErrors,
    LoginResponses,
    ResetPasswordData,
    ResetPasswordErrors,
    ResetPasswordResponses,
    SyncLocksData,
    SyncLocksErrors,
    SyncLocksResponses,
} from "./types.gen"

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

/**
 * Add new credentials for an implemented vendor.
 */
export const addVendorData = <ThrowOnError extends boolean = false>(
    options: Options<AddVendorDataData, ThrowOnError>
) =>
    (options.client ?? client).post<
        AddVendorDataResponses,
        AddVendorDataErrors,
        ThrowOnError
    >({
        url: "/api/v1/vendor-data",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Reset the authenticated user's password.
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
    options: Options<ResetPasswordData, ThrowOnError>
) =>
    (options.client ?? client).post<
        ResetPasswordResponses,
        ResetPasswordErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/reset-password",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Create a new user (admin only).
 */
export const createUser = <ThrowOnError extends boolean = false>(
    options: Options<CreateUserData, ThrowOnError>
) =>
    (options.client ?? client).post<
        CreateUserResponses,
        CreateUserErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/create",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Login a user.
 */
export const login = <ThrowOnError extends boolean = false>(
    options: Options<LoginData, ThrowOnError>
) =>
    (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        url: "/api/v1/user/auth/login",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Get all users paginated.
 */
export const getUsersPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetUsersPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetUsersPagedResponses,
        GetUsersPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/user/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Delete an existing person by user id.
 */
export const deletePerson = <ThrowOnError extends boolean = false>(
    options: Options<DeletePersonData, ThrowOnError>
) =>
    (options.client ?? client).post<
        DeletePersonResponses,
        DeletePersonErrors,
        ThrowOnError
    >({
        url: "/api/v1/person/delete",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Create a new person that can be assigned to locks, roles, etc.
 */
export const createPerson = <ThrowOnError extends boolean = false>(
    options: Options<CreatePersonData, ThrowOnError>
) =>
    (options.client ?? client).post<
        CreatePersonResponses,
        CreatePersonErrors,
        ThrowOnError
    >({
        url: "/api/v1/person/create",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Get all persons paginated.
 */
export const getPersonsPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetPersonsPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetPersonsPagedResponses,
        GetPersonsPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/person/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Sync locks from ISEO. Creates/updates local locks and removes those no longer in ISEO.
 */
export const syncLocks = <ThrowOnError extends boolean = false>(
    options?: Options<SyncLocksData, ThrowOnError>
) =>
    (options?.client ?? client).post<
        SyncLocksResponses,
        SyncLocksErrors,
        ThrowOnError
    >({ url: "/api/v1/lock/sync", ...options })

/**
 * Get all locks paginated.
 */
export const getLocksPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetLocksPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetLocksPagedResponses,
        GetLocksPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/lock/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Get all audit logs paginated.
 */
export const getAllAuditLogsPaged = <ThrowOnError extends boolean = false>(
    options: Options<GetAllAuditLogsPagedData, ThrowOnError>
) =>
    (options.client ?? client).post<
        GetAllAuditLogsPagedResponses,
        GetAllAuditLogsPagedErrors,
        ThrowOnError
    >({
        url: "/api/v1/audit-logs/all",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Get one Vendor-Data.
 */
export const getVendorData = <ThrowOnError extends boolean = false>(
    options: Options<GetVendorDataData, ThrowOnError>
) =>
    (options.client ?? client).get<
        GetVendorDataResponses,
        GetVendorDataErrors,
        ThrowOnError
    >({ url: "/api/v1/vendor-data/{id}", ...options })

/**
 * Get all implemented lock vendors.
 */
export const implementedVendors = <ThrowOnError extends boolean = false>(
    options?: Options<ImplementedVendorsData, ThrowOnError>
) =>
    (options?.client ?? client).get<
        ImplementedVendorsResponses,
        unknown,
        ThrowOnError
    >({ url: "/api/v1/vendor-data/implemented", ...options })

/**
 * Get all Vendor-Datas.
 */
export const getAllVendorData = <ThrowOnError extends boolean = false>(
    options?: Options<GetAllVendorDataData, ThrowOnError>
) =>
    (options?.client ?? client).get<
        GetAllVendorDataResponses,
        GetAllVendorDataErrors,
        ThrowOnError
    >({ url: "/api/v1/vendor-data/all", ...options })

/**
 * Get a user by id.
 */
export const getUser = <ThrowOnError extends boolean = false>(
    options: Options<GetUserData, ThrowOnError>
) =>
    (options.client ?? client).get<
        GetUserResponses,
        GetUserErrors,
        ThrowOnError
    >({ url: "/api/v1/user/{id}", ...options })

/**
 * Get the total number of persons.
 */
export const getPersonsCount = <ThrowOnError extends boolean = false>(
    options?: Options<GetPersonsCountData, ThrowOnError>
) =>
    (options?.client ?? client).get<
        GetPersonsCountResponses,
        GetPersonsCountErrors,
        ThrowOnError
    >({ url: "/api/v1/person/count", ...options })
