// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
    CreatePersonData,
    CreatePersonErrors,
    CreatePersonResponses,
    DeletePersonData,
    DeletePersonErrors,
    DeletePersonResponses,
    LoginData,
    LoginErrors,
    LoginResponses,
    RegisterData,
    RegisterResponses,
} from "./types.gen"

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

export const register = <ThrowOnError extends boolean = false>(
    options: Options<RegisterData, ThrowOnError>
) =>
    (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
        url: "/api/v1/user/auth/register",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Login a user.
 */
export const login = <ThrowOnError extends boolean = false>(
    options: Options<LoginData, ThrowOnError>
) =>
    (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        url: "/api/v1/user/auth/login",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Delete an existing person by user id.
 */
export const deletePerson = <ThrowOnError extends boolean = false>(
    options: Options<DeletePersonData, ThrowOnError>
) =>
    (options.client ?? client).post<
        DeletePersonResponses,
        DeletePersonErrors,
        ThrowOnError
    >({
        url: "/api/v1/person/delete",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })

/**
 * Create a new person that can be assigned to locks, roles, etc.
 */
export const createPerson = <ThrowOnError extends boolean = false>(
    options: Options<CreatePersonData, ThrowOnError>
) =>
    (options.client ?? client).post<
        CreatePersonResponses,
        CreatePersonErrors,
        ThrowOnError
    >({
        url: "/api/v1/person/create",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    })
