// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: "http://localhost:8080" | (string & {})
}

export type SuccessResponse = {
    message: string
}

export type ErrorResponse = {
    message: string
    status: number
}

export type AddApiDataRequestSchema = {
    forApi: string
    baseUrl: string
    apiKey?: string
    apiUsername?: string
    apiPassword?: string
}

export type ResetPasswordUserResponseSchema = {
    userId: string
    jwtToken: string
}

export type ResetPasswordUserRequestSchema = {
    oldPassword: string
    newPassword: string
}

export type CreateUserResponseSchema = {
    id: string
    password: string
}

export type CreateUserRequestSchema = {
    firstname: string
    lastname: string
    username: string
    email: string
}

export type LoginUserResponseSchema = {
    userId: string
    jwtToken: string
}

export type LoginUserRequestSchema = {
    username: string
    password: string
}

export type GetUsersPagedResponseSchema = {
    page: PageSchemaUserSchema
}

export type PageSchemaUserSchema = {
    content: Array<UserSchema>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type UserSchema = {
    id: string
    role: "ADMIN" | "USER"
    firstname: string
    lastname: string
    username: string
    email: string
    mustChangePassword: boolean
    isActive: boolean
}

export type GetUsersPagedRequestSchema = {
    filter: UserFilterSchema
    page: number
    size: number
}

export type UserFilterSchema = {
    search?: string
}

export type DeletePersonResponseSchema = {
    id: string
}

export type DeletePersonRequestSchema = {
    id: string
}

export type CreatePersonResponseSchema = {
    id: string
}

export type CreatePersonRequestSchema = {
    firstname: string
    lastname: string
    email: string
}

export type ExternalApiIdentitySchema = {
    api: string
    externalId: string
}

export type GetPersonsPagedResponseSchema = {
    page: PageSchemaPersonSchema
}

export type PageSchemaPersonSchema = {
    content: Array<PersonSchema>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type PersonSchema = {
    id: string
    firstname: string
    lastname: string
    email: string
    apiIdentities: Array<ExternalApiIdentitySchema>
}

export type GetPersonsPagedRequestSchema = {
    filter: PersonFilterSchema
    page: number
    size: number
}

export type PersonFilterSchema = {
    search?: string
}

export type SyncLocksResponseSchema = {
    synced: number
    deleted: number
}

export type GetLocksPagedResponseSchema = {
    page: PageSchemaLockSchema
}

export type LockSchema = {
    id: string
    name: string
    serialNumber: string
    metadata: Array<MetadataEntrySchema>
    apiIdentity?: ExternalApiIdentitySchema
}

export type MetadataEntrySchema = {
    key: string
    value: string
}

export type PageSchemaLockSchema = {
    content: Array<LockSchema>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type GetLocksPagedRequestSchema = {
    page: number
    size: number
}

export type GetAuditLogResponseDto = {
    id: string
    message: string
    performedByUserId: string
    createdAt: string
}

export type GetAuditLogsPagedResponseDto = {
    page: PageGetAuditLogResponseDto
}

export type PageGetAuditLogResponseDto = {
    content: Array<GetAuditLogResponseDto>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type AuditLogFilterDto = {
    fromDate?: string
    toDate?: string
    performedByUserId?: string
}

export type GetAllAuditLogsPagedRequestDto = {
    page?: number
    size?: number
    filter?: AuditLogFilterDto
}

export type GetVendorDataResponseDto = {
    id: string
    forApi: string
    baseUrl: string
    apiKey?: string
    apiUsername?: string
    apiPassword?: string
    vendorConnectionState: string
    lastChecked: number
}

export type GetImplementedVendorsResponseDto = {
    apis: Array<string>
}

export type GetUserResponseSchema = {
    user: UserSchema
}

export type CountPersonsResponseSchema = {
    count: number
}

export type AddVendorDataData = {
    body: AddApiDataRequestSchema
    path?: never
    query?: never
    url: "/api/v1/vendor-data"
}

export type AddVendorDataErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * The 'forApi' value was not valid.
     */
    422: ErrorResponse
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type AddVendorDataError = AddVendorDataErrors[keyof AddVendorDataErrors]

export type AddVendorDataResponses = {
    /**
     * Success
     */
    200: SuccessResponse
}

export type AddVendorDataResponse =
    AddVendorDataResponses[keyof AddVendorDataResponses]

export type ResetPasswordData = {
    body: ResetPasswordUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/reset-password"
}

export type ResetPasswordErrors = {
    /**
     * Invalid reset-password request.
     */
    400: ErrorResponse
    /**
     * Wrong old password.
     */
    401: ErrorResponse
    /**
     * User not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors]

export type ResetPasswordResponses = {
    /**
     * Success
     */
    200: ResetPasswordUserResponseSchema
}

export type ResetPasswordResponse =
    ResetPasswordResponses[keyof ResetPasswordResponses]

export type CreateUserData = {
    body: CreateUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/create"
}

export type CreateUserErrors = {
    /**
     * Invalid request (e.g. invalid requestor ID, lastname, firstname, email or username).
     */
    400: ErrorResponse
    /**
     * Requestor is not an admin.
     */
    401: ErrorResponse
    /**
     * Requestor not found.
     */
    404: ErrorResponse
    /**
     * Username or email already exists.
     */
    409: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors]

export type CreateUserResponses = {
    /**
     * User successfully created.
     */
    201: CreateUserResponseSchema
}

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses]

export type LoginData = {
    body: LoginUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/auth/login"
}

export type LoginErrors = {
    /**
     * Invalid username or password.
     */
    400: ErrorResponse
    /**
     * The username was not found.
     */
    404: ErrorResponse
}

export type LoginError = LoginErrors[keyof LoginErrors]

export type LoginResponses = {
    /**
     * Success
     */
    200: LoginUserResponseSchema
}

export type LoginResponse = LoginResponses[keyof LoginResponses]

export type GetUsersPagedData = {
    body: GetUsersPagedRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/all"
}

export type GetUsersPagedErrors = {
    /**
     * Invalid page or size.
     */
    400: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetUsersPagedError = GetUsersPagedErrors[keyof GetUsersPagedErrors]

export type GetUsersPagedResponses = {
    /**
     * Success
     */
    200: GetUsersPagedResponseSchema
}

export type GetUsersPagedResponse =
    GetUsersPagedResponses[keyof GetUsersPagedResponses]

export type DeletePersonData = {
    body: DeletePersonRequestSchema
    path?: never
    query?: never
    url: "/api/v1/person/delete"
}

export type DeletePersonErrors = {
    /**
     * Not a valid person id.
     */
    400: ErrorResponse
    /**
     * Person not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type DeletePersonError = DeletePersonErrors[keyof DeletePersonErrors]

export type DeletePersonResponses = {
    /**
     * Success
     */
    200: DeletePersonResponseSchema
}

export type DeletePersonResponse =
    DeletePersonResponses[keyof DeletePersonResponses]

export type CreatePersonData = {
    body: CreatePersonRequestSchema
    path?: never
    query?: never
    url: "/api/v1/person/create"
}

export type CreatePersonErrors = {
    /**
     * Invalid email, first name or last name.
     */
    400: ErrorResponse
    /**
     * The email is already taken.
     */
    409: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type CreatePersonError = CreatePersonErrors[keyof CreatePersonErrors]

export type CreatePersonResponses = {
    /**
     * Success
     */
    200: CreatePersonResponseSchema
}

export type CreatePersonResponse =
    CreatePersonResponses[keyof CreatePersonResponses]

export type GetPersonsPagedData = {
    body: GetPersonsPagedRequestSchema
    path?: never
    query?: never
    url: "/api/v1/person/all"
}

export type GetPersonsPagedErrors = {
    /**
     * Invalid page or size.
     */
    400: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetPersonsPagedError =
    GetPersonsPagedErrors[keyof GetPersonsPagedErrors]

export type GetPersonsPagedResponses = {
    /**
     * Success
     */
    200: GetPersonsPagedResponseSchema
}

export type GetPersonsPagedResponse =
    GetPersonsPagedResponses[keyof GetPersonsPagedResponses]

export type SyncLocksData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/lock/sync"
}

export type SyncLocksErrors = {
    /**
     * Something went wrong.
     */
    500: ErrorResponse
}

export type SyncLocksError = SyncLocksErrors[keyof SyncLocksErrors]

export type SyncLocksResponses = {
    /**
     * Sync completed successfully.
     */
    200: SyncLocksResponseSchema
}

export type SyncLocksResponse = SyncLocksResponses[keyof SyncLocksResponses]

export type GetLocksPagedData = {
    body: GetLocksPagedRequestSchema
    path?: never
    query?: never
    url: "/api/v1/lock/all"
}

export type GetLocksPagedErrors = {
    /**
     * Invalid page or size.
     */
    400: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetLocksPagedError = GetLocksPagedErrors[keyof GetLocksPagedErrors]

export type GetLocksPagedResponses = {
    /**
     * Success
     */
    200: GetLocksPagedResponseSchema
}

export type GetLocksPagedResponse =
    GetLocksPagedResponses[keyof GetLocksPagedResponses]

export type GetAllAuditLogsPagedData = {
    body: GetAllAuditLogsPagedRequestDto
    path?: never
    query?: never
    url: "/api/v1/audit-logs/all"
}

export type GetAllAuditLogsPagedErrors = {
    /**
     * Invalid page or size.
     */
    400: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetAllAuditLogsPagedError =
    GetAllAuditLogsPagedErrors[keyof GetAllAuditLogsPagedErrors]

export type GetAllAuditLogsPagedResponses = {
    /**
     * Success
     */
    200: GetAuditLogsPagedResponseDto
}

export type GetAllAuditLogsPagedResponse =
    GetAllAuditLogsPagedResponses[keyof GetAllAuditLogsPagedResponses]

export type GetVendorDataData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: "/api/v1/vendor-data/{id}"
}

export type GetVendorDataErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type GetVendorDataError = GetVendorDataErrors[keyof GetVendorDataErrors]

export type GetVendorDataResponses = {
    /**
     * Success
     */
    200: GetVendorDataResponseDto
}

export type GetVendorDataResponse =
    GetVendorDataResponses[keyof GetVendorDataResponses]

export type ImplementedVendorsData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/vendor-data/implemented"
}

export type ImplementedVendorsResponses = {
    /**
     * Success
     */
    200: GetImplementedVendorsResponseDto
}

export type ImplementedVendorsResponse =
    ImplementedVendorsResponses[keyof ImplementedVendorsResponses]

export type GetAllVendorDataData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/vendor-data/all"
}

export type GetAllVendorDataErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type GetAllVendorDataError =
    GetAllVendorDataErrors[keyof GetAllVendorDataErrors]

export type GetAllVendorDataResponses = {
    /**
     * Success
     */
    200: Array<GetVendorDataResponseDto>
}

export type GetAllVendorDataResponse =
    GetAllVendorDataResponses[keyof GetAllVendorDataResponses]

export type GetUserData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: "/api/v1/user/{id}"
}

export type GetUserErrors = {
    /**
     * Invalid id.
     */
    400: ErrorResponse
    /**
     * User not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetUserError = GetUserErrors[keyof GetUserErrors]

export type GetUserResponses = {
    /**
     * Success
     */
    200: GetUserResponseSchema
}

export type GetUserResponse = GetUserResponses[keyof GetUserResponses]

export type GetPersonsCountData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/person/count"
}

export type GetPersonsCountErrors = {
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetPersonsCountError =
    GetPersonsCountErrors[keyof GetPersonsCountErrors]

export type GetPersonsCountResponses = {
    /**
     * Success
     */
    200: CountPersonsResponseSchema
}

export type GetPersonsCountResponse =
    GetPersonsCountResponses[keyof GetPersonsCountResponses]
