// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: "http://localhost:8080" | (string & {})
}

export type SuccessResponse = {
    message: string
    status: number
}

export type ErrorResponse = {
    message: string
    status: number
}

export type MetadataEntrySchema = {
    key: string
    value: string
}

export type UpdateVendorDataRequestSchema = {
    forApi: string
    baseUrl?: string
    apiKey?: string
    apiUsername?: string
    apiPassword?: string
    metadata?: Array<MetadataEntrySchema>
}

export type AddVendorDataRequestSchema = {
    forApi: string
    baseUrl: string
    apiKey?: string
    apiUsername?: string
    apiPassword?: string
    metadata?: Array<MetadataEntrySchema>
}

export type ResetPasswordUserResponseSchema = {
    userId: string
    jwtToken: string
}

export type ResetPasswordUserRequestSchema = {
    oldPassword: string
    newPassword: string
}

export type RequestUserPasswordChangeRequestSchema = {
    userId: string
}

export type EditUserRequestSchema = {
    userId: string
    firstname?: string
    lastname?: string
    username?: string
    email?: string
}

export type DeactivateUserRequestSchema = {
    userId: string
}

export type CreateUserResponseSchema = {
    id: string
    password: string
}

export type CreateUserRequestSchema = {
    firstname: string
    lastname: string
    username: string
    email: string
}

export type ChangeUserRoleRequestSchema = {
    userId: string
    role: "ADMIN" | "USER"
}

export type LoginUserResponseSchema = {
    userId: string
    jwtToken: string
}

export type LoginUserRequestSchema = {
    username: string
    password: string
}

export type GetUsersPagedResponseSchema = {
    page: PageSchemaUserSchema
}

export type PageSchemaUserSchema = {
    content: Array<UserSchema>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type UserSchema = {
    id: string
    role: "ADMIN" | "USER"
    firstname: string
    lastname: string
    username: string
    email: string
    mustChangePassword: boolean
    isActive: boolean
}

export type GetUsersPagedRequestSchema = {
    filter: UserFilterSchema
    page: number
    size: number
}

export type UserFilterSchema = {
    search?: string
}

export type AdminResetPasswordUserResponseSchema = {
    userId: string
    password: string
}

export type AdminResetPasswordUserRequestSchema = {
    userId: string
}

export type ActivateUserRequestSchema = {
    userId: string
}

export type DeletePersonResponseSchema = {
    id: string
}

export type DeletePersonRequestSchema = {
    id: string
}

export type CreatePersonResponseSchema = {
    id: string
}

export type CreatePersonRequestSchema = {
    firstname: string
    lastname: string
    email: string
}

export type ExternalApiIdentitySchema = {
    api: string
    externalId: string
}

export type GetPersonsPagedResponseSchema = {
    page: PageSchemaPersonSchema
}

export type PageSchemaPersonSchema = {
    content: Array<PersonSchema>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type PersonSchema = {
    id: string
    firstname: string
    lastname: string
    email: string
    apiIdentities: Array<ExternalApiIdentitySchema>
}

export type GetPersonsPagedRequestSchema = {
    filter: PersonFilterSchema
    page: number
    size: number
}

export type PersonFilterSchema = {
    search?: string
}

export type SyncLocksResponseSchema = {
    synced: number
    deleted: number
}

export type GetLocksPagedResponseSchema = {
    page: PageSchemaLockSchema
}

export type LockSchema = {
    id: string
    name: string
    serialNumber: string
    metadata: Array<MetadataEntrySchema>
    apiIdentity?: ExternalApiIdentitySchema
}

export type PageSchemaLockSchema = {
    content: Array<LockSchema>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type GetLocksPagedRequestSchema = {
    page: number
    size: number
}

export type GetAuditLogResponseDto = {
    id: string
    message: string
    performedByUserId: string
    createdAt: number
}

export type GetAuditLogsPagedResponseDto = {
    page: PageGetAuditLogResponseDto
}

export type PageGetAuditLogResponseDto = {
    content: Array<GetAuditLogResponseDto>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type AuditLogFilterDto = {
    fromDate?: string
    toDate?: string
    performedByUserId?: string
}

export type GetAllAuditLogsPagedRequestDto = {
    page?: number
    size?: number
    filter?: AuditLogFilterDto
}

export type GrantAccessResponseSchema = {
    grantId: string
    vendor: string
    vendorExternalId: string
}

export type GrantAccessRequestSchema = {
    personId: string
    lockId: string
    start: string
    end: string
}

export type RevokeAccessResponseSchema = {
    grantId: string
    vendor: string
}

export type RevokeAccessRequestSchema = {
    grantId: string
}

export type AccessGrantSchema = {
    grantId: string
    personId: string
    lockId: string
    start: string
    end: string
    vendor?: string
    vendorExternalId?: string
}

export type GetAccessGrantsPagedResponseSchema = {
    page: PageSchemaAccessGrantSchema
}

export type PageSchemaAccessGrantSchema = {
    content: Array<AccessGrantSchema>
    page: number
    size: number
    totalElements: number
    totalPages: number
    isFirst: boolean
    isLast: boolean
    isEmpty: boolean
}

export type GetAccessGrantsPagedRequestSchema = {
    page: number
    size: number
    personId?: string
    lockId?: string
}

export type GetVendorDataResponseDto = {
    id: string
    forApi: string
    baseUrl: string
    apiKey?: string
    apiUsername?: string
    apiPassword?: string
    vendorConnectionState: string
    lastChecked: number
    metadata?: Array<MetadataEntryDto>
}

export type MetadataEntryDto = {
    key: string
    value: string
}

export type GetImplementedVendorsResponseDto = {
    apis: Array<string>
}

export type GetVendorSpecificDefinitionsResponseDto = {
    vendorName: string
    vendorSpecificFields: Array<VendorSpecificFieldDto>
}

export type VendorSpecificFieldDto = {
    name: string
    type: string
    description: string
}

export type GetUserResponseSchema = {
    user: UserSchema
}

export type GetPersonResponseSchema = {
    person: PersonSchema
}

export type CountPersonsResponseSchema = {
    count: number
}

export type CountLocksResponseSchema = {
    count: number
}

export type AddVendorDataData = {
    body: AddVendorDataRequestSchema
    path?: never
    query?: never
    url: "/api/v1/vendor-data"
}

export type AddVendorDataErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * The 'forApi' value was not valid.
     */
    422: ErrorResponse
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type AddVendorDataError = AddVendorDataErrors[keyof AddVendorDataErrors]

export type AddVendorDataResponses = {
    /**
     * Success
     */
    200: SuccessResponse
}

export type AddVendorDataResponse =
    AddVendorDataResponses[keyof AddVendorDataResponses]

export type UpdateVendorDataData = {
    body: UpdateVendorDataRequestSchema
    path?: never
    query?: never
    url: "/api/v1/vendor-data"
}

export type UpdateVendorDataErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type UpdateVendorDataError =
    UpdateVendorDataErrors[keyof UpdateVendorDataErrors]

export type UpdateVendorDataResponses = {
    /**
     * Success
     */
    200: SuccessResponse
}

export type UpdateVendorDataResponse =
    UpdateVendorDataResponses[keyof UpdateVendorDataResponses]

export type ResetPasswordData = {
    body: ResetPasswordUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/reset-password"
}

export type ResetPasswordErrors = {
    /**
     * Invalid reset-password request.
     */
    400: ErrorResponse
    /**
     * Wrong old password.
     */
    401: ErrorResponse
    /**
     * User not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors]

export type ResetPasswordResponses = {
    /**
     * Success
     */
    200: ResetPasswordUserResponseSchema
}

export type ResetPasswordResponse =
    ResetPasswordResponses[keyof ResetPasswordResponses]

export type RequestPasswordChangeData = {
    body: RequestUserPasswordChangeRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/request-password-change"
}

export type RequestPasswordChangeErrors = {
    /**
     * Invalid requestor or target user ID.
     */
    400: ErrorResponse
    /**
     * Requestor is not an admin.
     */
    401: ErrorResponse
    /**
     * Requestor or target user not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type RequestPasswordChangeError =
    RequestPasswordChangeErrors[keyof RequestPasswordChangeErrors]

export type RequestPasswordChangeResponses = {
    /**
     * Password change successfully requested.
     */
    200: unknown
}

export type EditUserData = {
    body: EditUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/edit-user"
}

export type EditUserErrors = {
    /**
     * Invalid ID, firstname, lastname, username or email.
     */
    400: ErrorResponse
    /**
     * Requestor is not an admin.
     */
    401: ErrorResponse
    /**
     * Requestor or target user not found, or email/username already exists.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type EditUserError = EditUserErrors[keyof EditUserErrors]

export type EditUserResponses = {
    /**
     * User successfully edited.
     */
    200: unknown
}

export type DeactivateUserData = {
    body: DeactivateUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/deactivate-user"
}

export type DeactivateUserErrors = {
    /**
     * Invalid ID, or user is already inactive.
     */
    400: ErrorResponse
    /**
     * Requestor is not an admin.
     */
    401: ErrorResponse
    /**
     * Requestor or target user not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type DeactivateUserError =
    DeactivateUserErrors[keyof DeactivateUserErrors]

export type DeactivateUserResponses = {
    /**
     * User successfully deactivated.
     */
    200: unknown
}

export type CreateUserData = {
    body: CreateUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/create"
}

export type CreateUserErrors = {
    /**
     * Invalid request (e.g. invalid requestor ID, lastname, firstname, email or username).
     */
    400: ErrorResponse
    /**
     * Requestor is not an admin.
     */
    401: ErrorResponse
    /**
     * Requestor not found.
     */
    404: ErrorResponse
    /**
     * Username or email already exists.
     */
    409: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors]

export type CreateUserResponses = {
    /**
     * User successfully created.
     */
    201: CreateUserResponseSchema
}

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses]

export type ChangeRoleData = {
    body: ChangeUserRoleRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/change-role"
}

export type ChangeRoleErrors = {
    /**
     * Invalid requestor or target user ID.
     */
    400: ErrorResponse
    /**
     * Requestor is not an admin.
     */
    401: ErrorResponse
    /**
     * Requestor or target user not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type ChangeRoleError = ChangeRoleErrors[keyof ChangeRoleErrors]

export type ChangeRoleResponses = {
    /**
     * User role successfully changed.
     */
    200: unknown
}

export type LoginData = {
    body: LoginUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/auth/login"
}

export type LoginErrors = {
    /**
     * Invalid username or password.
     */
    400: ErrorResponse
    /**
     * The username was not found.
     */
    404: ErrorResponse
}

export type LoginError = LoginErrors[keyof LoginErrors]

export type LoginResponses = {
    /**
     * Success
     */
    200: LoginUserResponseSchema
}

export type LoginResponse = LoginResponses[keyof LoginResponses]

export type GetUsersPagedData = {
    body: GetUsersPagedRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/all"
}

export type GetUsersPagedErrors = {
    /**
     * Invalid page or size.
     */
    400: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetUsersPagedError = GetUsersPagedErrors[keyof GetUsersPagedErrors]

export type GetUsersPagedResponses = {
    /**
     * Success
     */
    200: GetUsersPagedResponseSchema
}

export type GetUsersPagedResponse =
    GetUsersPagedResponses[keyof GetUsersPagedResponses]

export type AdminResetPasswordData = {
    body: AdminResetPasswordUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/admin-reset-password"
}

export type AdminResetPasswordErrors = {
    /**
     * Invalid requestor or target user ID.
     */
    400: ErrorResponse
    /**
     * Requestor is not an admin.
     */
    401: ErrorResponse
    /**
     * Requestor or target user not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type AdminResetPasswordError =
    AdminResetPasswordErrors[keyof AdminResetPasswordErrors]

export type AdminResetPasswordResponses = {
    /**
     * Password successfully reset.
     */
    201: AdminResetPasswordUserResponseSchema
}

export type AdminResetPasswordResponse =
    AdminResetPasswordResponses[keyof AdminResetPasswordResponses]

export type ActivateUserData = {
    body: ActivateUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/activate-user"
}

export type ActivateUserErrors = {
    /**
     * Invalid ID, or user is already active.
     */
    400: ErrorResponse
    /**
     * Requestor is not an admin.
     */
    401: ErrorResponse
    /**
     * Requestor or target user not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type ActivateUserError = ActivateUserErrors[keyof ActivateUserErrors]

export type ActivateUserResponses = {
    /**
     * User successfully activated.
     */
    200: unknown
}

export type DeletePersonData = {
    body: DeletePersonRequestSchema
    path?: never
    query?: never
    url: "/api/v1/person/delete"
}

export type DeletePersonErrors = {
    /**
     * Not a valid person id.
     */
    400: ErrorResponse
    /**
     * Person not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type DeletePersonError = DeletePersonErrors[keyof DeletePersonErrors]

export type DeletePersonResponses = {
    /**
     * Success
     */
    200: DeletePersonResponseSchema
}

export type DeletePersonResponse =
    DeletePersonResponses[keyof DeletePersonResponses]

export type CreatePersonData = {
    body: CreatePersonRequestSchema
    path?: never
    query?: never
    url: "/api/v1/person/create"
}

export type CreatePersonErrors = {
    /**
     * Invalid email, first name or last name.
     */
    400: ErrorResponse
    /**
     * The email is already taken.
     */
    409: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type CreatePersonError = CreatePersonErrors[keyof CreatePersonErrors]

export type CreatePersonResponses = {
    /**
     * Success
     */
    200: CreatePersonResponseSchema
}

export type CreatePersonResponse =
    CreatePersonResponses[keyof CreatePersonResponses]

export type GetPersonsPagedData = {
    body: GetPersonsPagedRequestSchema
    path?: never
    query?: never
    url: "/api/v1/person/all"
}

export type GetPersonsPagedErrors = {
    /**
     * Invalid page or size.
     */
    400: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetPersonsPagedError =
    GetPersonsPagedErrors[keyof GetPersonsPagedErrors]

export type GetPersonsPagedResponses = {
    /**
     * Success
     */
    200: GetPersonsPagedResponseSchema
}

export type GetPersonsPagedResponse =
    GetPersonsPagedResponses[keyof GetPersonsPagedResponses]

export type SyncLocksData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/lock/sync"
}

export type SyncLocksErrors = {
    /**
     * Something went wrong.
     */
    500: ErrorResponse
}

export type SyncLocksError = SyncLocksErrors[keyof SyncLocksErrors]

export type SyncLocksResponses = {
    /**
     * Sync completed successfully.
     */
    200: SyncLocksResponseSchema
}

export type SyncLocksResponse = SyncLocksResponses[keyof SyncLocksResponses]

export type GetLocksPagedData = {
    body: GetLocksPagedRequestSchema
    path?: never
    query?: never
    url: "/api/v1/lock/all"
}

export type GetLocksPagedErrors = {
    /**
     * Invalid page or size.
     */
    400: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetLocksPagedError = GetLocksPagedErrors[keyof GetLocksPagedErrors]

export type GetLocksPagedResponses = {
    /**
     * Success
     */
    200: GetLocksPagedResponseSchema
}

export type GetLocksPagedResponse =
    GetLocksPagedResponses[keyof GetLocksPagedResponses]

export type GetAllAuditLogsPagedData = {
    body: GetAllAuditLogsPagedRequestDto
    path?: never
    query?: never
    url: "/api/v1/audit-logs/all"
}

export type GetAllAuditLogsPagedErrors = {
    /**
     * Invalid page or size.
     */
    400: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetAllAuditLogsPagedError =
    GetAllAuditLogsPagedErrors[keyof GetAllAuditLogsPagedErrors]

export type GetAllAuditLogsPagedResponses = {
    /**
     * Success
     */
    200: GetAuditLogsPagedResponseDto
}

export type GetAllAuditLogsPagedResponse =
    GetAllAuditLogsPagedResponses[keyof GetAllAuditLogsPagedResponses]

export type GrantAccessData = {
    body: GrantAccessRequestSchema
    path?: never
    query?: never
    url: "/api/v1/access-grant"
}

export type GrantAccessErrors = {
    /**
     * Invalid request.
     */
    400: ErrorResponse
    /**
     * Person or lock not found.
     */
    404: ErrorResponse
    /**
     * Person not provisioned on the lock's vendor.
     */
    422: ErrorResponse
    /**
     * Something went wrong.
     */
    500: ErrorResponse
}

export type GrantAccessError = GrantAccessErrors[keyof GrantAccessErrors]

export type GrantAccessResponses = {
    /**
     * Access granted.
     */
    201: GrantAccessResponseSchema
}

export type GrantAccessResponse =
    GrantAccessResponses[keyof GrantAccessResponses]

export type RevokeAccessData = {
    body: RevokeAccessRequestSchema
    path?: never
    query?: never
    url: "/api/v1/access-grant/revoke"
}

export type RevokeAccessErrors = {
    /**
     * Invalid request.
     */
    400: ErrorResponse
    /**
     * Access grant not found.
     */
    404: ErrorResponse
    /**
     * Access grant is not present on any vendor.
     */
    422: ErrorResponse
    /**
     * Something went wrong.
     */
    500: ErrorResponse
}

export type RevokeAccessError = RevokeAccessErrors[keyof RevokeAccessErrors]

export type RevokeAccessResponses = {
    /**
     * Access revoked.
     */
    200: RevokeAccessResponseSchema
}

export type RevokeAccessResponse =
    RevokeAccessResponses[keyof RevokeAccessResponses]

export type GetAccessGrantsPagedData = {
    body: GetAccessGrantsPagedRequestSchema
    path?: never
    query?: never
    url: "/api/v1/access-grant/all"
}

export type GetAccessGrantsPagedErrors = {
    /**
     * Invalid page, size, personId or lockId.
     */
    400: ErrorResponse
    /**
     * Something went wrong.
     */
    500: ErrorResponse
}

export type GetAccessGrantsPagedError =
    GetAccessGrantsPagedErrors[keyof GetAccessGrantsPagedErrors]

export type GetAccessGrantsPagedResponses = {
    /**
     * Success.
     */
    200: GetAccessGrantsPagedResponseSchema
}

export type GetAccessGrantsPagedResponse =
    GetAccessGrantsPagedResponses[keyof GetAccessGrantsPagedResponses]

export type DeleteVendorDataData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: "/api/v1/vendor-data/{id}"
}

export type DeleteVendorDataErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type DeleteVendorDataError =
    DeleteVendorDataErrors[keyof DeleteVendorDataErrors]

export type DeleteVendorDataResponses = {
    /**
     * Success
     */
    200: SuccessResponse
}

export type DeleteVendorDataResponse =
    DeleteVendorDataResponses[keyof DeleteVendorDataResponses]

export type GetVendorDataData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: "/api/v1/vendor-data/{id}"
}

export type GetVendorDataErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Not Found
     */
    404: ErrorResponse
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type GetVendorDataError = GetVendorDataErrors[keyof GetVendorDataErrors]

export type GetVendorDataResponses = {
    /**
     * Success
     */
    200: GetVendorDataResponseDto
}

export type GetVendorDataResponse =
    GetVendorDataResponses[keyof GetVendorDataResponses]

export type ImplementedVendorsData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/vendor-data/implemented"
}

export type ImplementedVendorsResponses = {
    /**
     * Success
     */
    200: GetImplementedVendorsResponseDto
}

export type ImplementedVendorsResponse =
    ImplementedVendorsResponses[keyof ImplementedVendorsResponses]

export type GetVendorSpecificDefinitionsData = {
    body?: never
    path: {
        forVendor: string
    }
    query?: never
    url: "/api/v1/vendor-data/definitions/{forVendor}"
}

export type GetVendorSpecificDefinitionsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type GetVendorSpecificDefinitionsError =
    GetVendorSpecificDefinitionsErrors[keyof GetVendorSpecificDefinitionsErrors]

export type GetVendorSpecificDefinitionsResponses = {
    /**
     * Success
     */
    200: GetVendorSpecificDefinitionsResponseDto
}

export type GetVendorSpecificDefinitionsResponse =
    GetVendorSpecificDefinitionsResponses[keyof GetVendorSpecificDefinitionsResponses]

export type GetAllVendorDataData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/vendor-data/all"
}

export type GetAllVendorDataErrors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse
}

export type GetAllVendorDataError =
    GetAllVendorDataErrors[keyof GetAllVendorDataErrors]

export type GetAllVendorDataResponses = {
    /**
     * Success
     */
    200: Array<GetVendorDataResponseDto>
}

export type GetAllVendorDataResponse =
    GetAllVendorDataResponses[keyof GetAllVendorDataResponses]

export type GetUserData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: "/api/v1/user/{id}"
}

export type GetUserErrors = {
    /**
     * Invalid id.
     */
    400: ErrorResponse
    /**
     * User not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetUserError = GetUserErrors[keyof GetUserErrors]

export type GetUserResponses = {
    /**
     * Success
     */
    200: GetUserResponseSchema
}

export type GetUserResponse = GetUserResponses[keyof GetUserResponses]

export type GetPersonByIdData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: "/api/v1/person/{id}"
}

export type GetPersonByIdErrors = {
    /**
     * Not a valid person id.
     */
    400: ErrorResponse
    /**
     * Person not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetPersonByIdError = GetPersonByIdErrors[keyof GetPersonByIdErrors]

export type GetPersonByIdResponses = {
    /**
     * Success
     */
    200: GetPersonResponseSchema
}

export type GetPersonByIdResponse =
    GetPersonByIdResponses[keyof GetPersonByIdResponses]

export type GetPersonsCountData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/person/count"
}

export type GetPersonsCountErrors = {
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetPersonsCountError =
    GetPersonsCountErrors[keyof GetPersonsCountErrors]

export type GetPersonsCountResponses = {
    /**
     * Success
     */
    200: CountPersonsResponseSchema
}

export type GetPersonsCountResponse =
    GetPersonsCountResponses[keyof GetPersonsCountResponses]

export type GetLocksCountData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/lock/count"
}

export type GetLocksCountErrors = {
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type GetLocksCountError = GetLocksCountErrors[keyof GetLocksCountErrors]

export type GetLocksCountResponses = {
    /**
     * Success
     */
    200: CountLocksResponseSchema
}

export type GetLocksCountResponse =
    GetLocksCountResponses[keyof GetLocksCountResponses]
