// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: "http://localhost:8080" | (string & {})
}

export type RegisterUserRequestSchema = {
    username: string
    password: string
}

export type LoginUserResponseSchema = {
    userId: string
    jwtToken: string
}

export type ErrorResponse = {
    message: string
}

export type LoginUserRequestSchema = {
    username: string
    password: string
}

export type DeletePersonResponseSchema = {
    id: string
}

export type DeletePersonRequestSchema = {
    id: string
}

export type CreatePersonResponseSchema = {
    id: string
}

export type CreatePersonRequestSchema = {
    firstname: string
    lastname: string
    email: string
}

export type RegisterData = {
    body: RegisterUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/auth/register"
}

export type RegisterResponses = {
    /**
     * OK
     */
    200: unknown
}

export type LoginData = {
    body: LoginUserRequestSchema
    path?: never
    query?: never
    url: "/api/v1/user/auth/login"
}

export type LoginErrors = {
    /**
     * Invalid username or password.
     */
    400: ErrorResponse
    /**
     * The username was not found.
     */
    404: ErrorResponse
}

export type LoginError = LoginErrors[keyof LoginErrors]

export type LoginResponses = {
    /**
     * Success
     */
    200: LoginUserResponseSchema
}

export type LoginResponse = LoginResponses[keyof LoginResponses]

export type DeletePersonData = {
    body: DeletePersonRequestSchema
    path?: never
    query?: never
    url: "/api/v1/person/delete"
}

export type DeletePersonErrors = {
    /**
     * Not a valid person id.
     */
    400: ErrorResponse
    /**
     * Person not found.
     */
    404: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type DeletePersonError = DeletePersonErrors[keyof DeletePersonErrors]

export type DeletePersonResponses = {
    /**
     * Success
     */
    200: DeletePersonResponseSchema
}

export type DeletePersonResponse =
    DeletePersonResponses[keyof DeletePersonResponses]

export type CreatePersonData = {
    body: CreatePersonRequestSchema
    path?: never
    query?: never
    url: "/api/v1/person/create"
}

export type CreatePersonErrors = {
    /**
     * Invalid email, first name or last name.
     */
    400: ErrorResponse
    /**
     * The email is already taken.
     */
    409: ErrorResponse
    /**
     * Something went wrong...rip
     */
    500: ErrorResponse
}

export type CreatePersonError = CreatePersonErrors[keyof CreatePersonErrors]

export type CreatePersonResponses = {
    /**
     * Success
     */
    200: CreatePersonResponseSchema
}

export type CreatePersonResponse =
    CreatePersonResponses[keyof CreatePersonResponses]
